Switched to pyproject.toml workflow, removed an unneccessary module import
reichlab/jacques pull request #8
Opened 2024-05-28 15:28 UTC by benwrogers87

2024-06-17 16:20 UTC, elray1 requested changes
- Added a couple of comments, mostly minor, but a couple that rendered the code un-runnable.
 - After fixing a couple of those issues locally, the demo worked for me.
 - Could we add something to a README file with info about how to set up the development environment?

2024-06-17 16:20 UTC, elray1 commented on pyproject.toml
> +    "tf-keras>=2.16,<3",
do we use Keras in this package?  If not, let's remove this dependency.

2024-06-17 16:20 UTC, elray1 commented on pyproject.toml
> +    "matplotlib>=3.9.0",
Do we use matplotlib in the package itself, or just in the documentation?  If just in the documentation, let's move this dependency to a separate block, maybe called "doc" or something.  Becky may know if there's a standard name for this.

2024-06-17 16:20 UTC, elray1 commented on jacques/kernels.py
> +    diff_chol_prod = tf.expand_dims(tf.matmul(diffs, B_chol, -1))
The code did not run for me with this change in place.

2024-06-18 18:37 UTC, benwrogers87 commented
I believe that I fixed everything listed here. Let me know if it works locally for you!

2024-06-24 16:09 UTC, elray1 reviewed
one minor change to readme, otherwise lgtm

2024-06-24 18:48 UTC, elray1 submitted a review, later dismissed

2024-12-19 15:38 UTC, rogersbw commented
I believe we had a reviewed and approved a PR that never got merged. Looking to get the main repo caught up to start pushing changes again.

2024-12-19 20:20 UTC, elray1 submitted a review, later dismissed
had a couple of questions, but approving in case you think it's good to go

2024-12-19 20:56 UTC, elray1 approved these changes

2024-12-19 21:29 UTC, merged